from __future__ import annotations
from collections.abc import Mapping

# requests per second, float (e.g., 1 req / 10 seconds -> 0.1)
_METHOD_RPS: Mapping[str, float] = {
    "getSettings": 1,
    "setSettings": 1,
    "getStateInstance": 1,
    "getStatusInstance": 1,
    "reboot": 1,
    "logout": 1,
    "qr": 3,
    "scanQrCode": 1,
    "setProfilePicture": 0.1,
    "getWaSettings": 1,
    "sendFileByUpload": 50,
    "receiveNotification": 100,
    "deleteNotification": 100,
    "downloadFile": 5,
    "getChatHistory": 1,
    "getMessage": 10,
    "lastIncomingMessages": 1,
    "lastOutgoingMessages": 1,
    "createGroup": 1,
    "updateGroupName": 1,
    "getGroupData": 1,
    "addGroupParticipant": 10,
    "removeGroupParticipant": 10,
    "setGroupAdmin": 10,
    "removeAdmin": 10,
    "setGroupPicture": 1,
    "leaveGroup": 10,
    "readChat": 10,
    "getDeviceInfo": 1,
    "checkWhatsapp": 10,
    "getAvatar": 10,
    "getContacts": 1,
    "getContactInfo": 1,
    "editMessage": 1,
    "deleteMessage": 10,
    "archiveChat": 10,
    "unarchiveChat": 10,
    "setDisappearingChat": 1,
    "sendMessage": 50,
    "sendButtons": 50,
    "sendTemplateButtons": 50,
    "sendListMessage": 50,
    "sendLocation": 50,
    "sendLink": 50,
    "sendContact": 50,
    "sendFileByUrl": 50,
    "sendPoll": 50,
    "getMessagesCount": 1,
    "showMessagesQueue": 1,
    "clearMessagesQueue": 1,
    "getWebhooksCount": 1,
    "clearWebhooksQueue": 1,
    "sendTemplate": 50,
    "forwardMessages": 50,
    "deleteStatus": 10,
    "getIncomingStatuses": 1,
    "getOutgoingStatuses": 1,
    "getStatusStatistic": 1,
    "sendTextStatus": 5,
    "sendVoiceStatus": 5,
    "sendMediaStatus": 5,
}

DEFAULT_RPS = 1